# Generated by Django 3.1.1 on 2020-09-08 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Groups', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manager_name', models.CharField(choices=[('Hans-Dieter Flick', 'Hans-Dieter Flick'), ('Thomas Tuchel', 'Thomas Tuchel'), ('Pep Guardiola', 'Pep Guardiola'), ('Jürgen Klopp', 'Jürgen Klopp'), ('Ronald Koeman', 'Ronald Koeman'), ('Frank Lampard', 'Frank Lampard'), ('Zinédine Zidane', 'Zinédine Zidane'), ('Diego Simeone', 'Diego Simeone'), ('José Mourinho', 'José Mourinho'), ('Antonio Conte', 'Antonio Conte'), ('Andrea Pirlo', 'Andrea Pirlo'), ('Gennaro Gattuso', 'Gennaro Gattuso'), ('Lucien Favre', 'Lucien Favre'), ('Julian Nagelsmann', 'Julian Nagelsmann'), ('Jorge Jesus', 'Jorge Jesus'), ('Gian Piero Gasperini', 'Gian Piero Gasperini'), ('Rudi Garcia', 'Rudi Garcia'), ('Peter Bosz', 'Peter Bosz'), ('Javi Gracia', 'Javi Gracia'), ('Erik ten Hag', 'Erik ten Hag'), ('Christophe Galtier', 'Christophe Galtier'), ('Sergey Semak', 'Sergey Semak'), ('Luís Castro', 'Luís Castro'), ('Jesse Marsch', 'Jesse Marsch'), ('Philippe Clement', 'Philippe Clement'), ('Hannes Wolf', 'Hannes Wolf'), ('Pedro Martins', 'Pedro Martins'), ('Zoran Mamic', 'Zoran Mamic'), ('Marko Nikolic', 'Marko Nikolic'), ('Fatih Terim', 'Fatih Terim'), ('Dejan Stanković', 'Dejan Stanković'), ('Jindrich Trpisovsky', 'Jindrich Trpisovsky')], max_length=100)),
                ('Manager_team', models.CharField(choices=[('Bayern Munich', 'Bayern Munich'), ('Paris Saint-Germain', 'Paris Saint-Germain'), ('Manchester City', 'Manchester City'), ('Liverpool FC', 'Liverpool FC'), ('FC Barcelona', 'FC Barcelona'), ('Chelsea FC', 'Chelsea FC'), ('Real Madrid', 'Real Madrid'), ('Atlético Madrid', 'Atlético Madrid'), ('Tottenham Hotspur', 'Tottenham Hotspur'), ('Inter Milan', 'Inter Milan'), ('Juventus FC', 'Juventus FC'), ('SSC Napoli', 'SSC Napoli'), ('Borussia Dortmund', 'Borussia Dortmund'), ('RB Leipzi', 'RB Leipzi'), ('SL Benfica', 'SL Benfica'), ('Atalanta BC', 'Atalanta BC'), ('Olympique Lyon', 'Olympique Lyon'), ('Bayer 04 Leverkusen', 'Bayer 04 Leverkusen'), ('Valencia CF', 'Valencia CF'), ('Ajax Amsterdam', 'Ajax Amsterdam'), ('LOSC Lille', 'LOSC Lille'), ('Zenit St. Petersburg', 'Zenit St. Petersburg'), ('Shakhtar Donetsk', 'Shakhtar Donetsk'), ('Red Bull Salzburg', 'Red Bull Salzburg'), ('Club Brugge KV', 'Club Brugge KV'), ('KRC Genk', 'KRC Genk'), ('Olympiacos Piraeus', 'Olympiacos Piraeus'), ('GNK Dinamo Zagreb', 'GNK Dinamo Zagreb'), ('Lokomotiv Moscow', 'Lokomotiv Moscow'), ('Galatasaray SK', 'Galatasaray SK'), ('Red Star Belgrade', 'Red Star Belgrade'), ('SK Slavia Prague', 'SK Slavia Prague')], max_length=100)),
                ('Manager_age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team1', models.CharField(max_length=100)),
                ('Team2', models.CharField(max_length=100)),
                ('Team3', models.CharField(max_length=100)),
                ('Team4', models.CharField(max_length=100)),
                ('TeamGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChampionsLeague.group')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.PositiveIntegerField()),
                ('Overall', models.PositiveIntegerField()),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChampionsLeague.club')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='Club_Manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='ChampionsLeague.manager'),
        ),
        migrations.AddField(
            model_name='club',
            name='Club_Name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ChampionsLeague.manager'),
        ),
        migrations.AddField(
            model_name='club',
            name='Relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ChampionsLeague.group'),
        ),
    ]
