# Generated by Django 3.1.1 on 2020-09-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='TeamGroups',
        ),
    ]
