# Generated by Django 3.1.1 on 2020-09-08 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0003_auto_20200908_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='Club_Name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ChampionsLeague.manager'),
        ),
    ]
