# Generated by Django 3.1.1 on 2020-09-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0004_auto_20200908_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.CharField(choices=[('Bayern Munich', 'Bayern Munich'), ('Paris Saint-Germain', 'Paris Saint-Germain'), ('Manchester City', 'Manchester City'), ('Liverpool FC', 'Liverpool FC'), ('FC Barcelona', 'FC Barcelona'), ('Chelsea FC', 'Chelsea FC'), ('Real Madrid', 'Real Madrid'), ('Atlético Madrid', 'Atlético Madrid'), ('Tottenham Hotspur', 'Tottenham Hotspur'), ('Inter Milan', 'Inter Milan'), ('Juventus FC', 'Juventus FC'), ('SSC Napoli', 'SSC Napoli'), ('Borussia Dortmund', 'Borussia Dortmund'), ('RB Leipzi', 'RB Leipzi'), ('SL Benfica', 'SL Benfica'), ('Atalanta BC', 'Atalanta BC'), ('Olympique Lyon', 'Olympique Lyon'), ('Bayer 04 Leverkusen', 'Bayer 04 Leverkusen'), ('Valencia CF', 'Valencia CF'), ('Ajax Amsterdam', 'Ajax Amsterdam'), ('LOSC Lille', 'LOSC Lille'), ('Zenit St. Petersburg', 'Zenit St. Petersburg'), ('Shakhtar Donetsk', 'Shakhtar Donetsk'), ('Red Bull Salzburg', 'Red Bull Salzburg'), ('Club Brugge KV', 'Club Brugge KV'), ('KRC Genk', 'KRC Genk'), ('Olympiacos Piraeus', 'Olympiacos Piraeus'), ('GNK Dinamo Zagreb', 'GNK Dinamo Zagreb'), ('Lokomotiv Moscow', 'Lokomotiv Moscow'), ('Galatasaray SK', 'Galatasaray SK'), ('Red Star Belgrade', 'Red Star Belgrade'), ('SK Slavia Prague', 'SK Slavia Prague')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='Club_Name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ChampionsLeague.allteams'),
        ),
    ]
