# Generated by Django 3.1.1 on 2020-09-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0006_auto_20200908_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ChampionsLeague.club'),
        ),
    ]
