# Generated by Django 3.1.1 on 2020-09-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0008_auto_20200908_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='Rating',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
