# Generated by Django 3.1.1 on 2020-09-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0009_club_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='Rating',
            new_name='Goals',
        ),
    ]
