# Generated by Django 3.1.1 on 2020-09-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0011_auto_20200910_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Goals',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
