# Generated by Django 3.1.1 on 2020-09-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0012_player_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='Overall',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
