# Generated by Django 3.1.1 on 2020-09-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0014_auto_20200910_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Name',
            field=models.CharField(choices=[('Lewandowski', 'Lewandowski'), ('Erling Braut Haaland', 'Erling Braut Haaland'), ('Serge Gnabry', 'Serge Gnabry'), ('Sterling', 'Sterling'), ('Depay', 'Depay'), ('Kane', 'Kane'), ('Mertens', 'Mertens'), ('Gabriel Jesus', 'Gabriel Jesus'), ('Josip Ilicic', 'Josip Ilicic'), ('Kylian Mbappe', 'Kylian Mbappe'), ('Icardi', 'Icardi'), ('Benzema', 'Benzema'), ('Luis Suárez', 'Luis Suárez'), ('Heung-Min Son', 'Heung-Min Son'), ('Lautaro Martínez', 'Lautaro Martínez'), ('Rodrygo', 'Rodrygo'), ('Mislav Orsic', 'Mislav Orsic'), ('Salah', 'Salah'), ('Forsberg', 'Forsberg'), ('Müller', 'Müller'), ('Cristiano Ronaldo', 'Cristiano Ronaldo'), ('M. Sabitzer', 'M. Sabitzer'), ('Timo Werner', 'Timo Werner'), ('Achraf Hakimi', 'Achraf Hakimi'), ('Quincy Promes', 'Quincy Promes'), ('Pasalic', 'Pasalic'), ('Tammy Abraham', 'Tammy Abraham'), ('Di María', 'Di María'), ('Neymar', 'Neymar'), ('Arkadiusz Milik', 'Arkadiusz Milik'), ('Paulo Dybala', 'Paulo Dybala'), ('Dani Olmo', 'Dani Olmo'), ('Oxlade-Chamberlain', 'Oxlade-Chamberlain'), ('Tolisso', 'Tolisso'), ('Perisic', 'Perisic'), ('João Félix', 'João Félix'), ('Hwang Hee-Chan', 'Hwang Hee-Chan'), ('Pizzi', 'Pizzi'), ('Coutinho', 'Coutinho'), ('Kingsley Coman', 'Kingsley Coman'), ('Lionel Messi', 'Lionel Messi'), ('Morata', 'Morata'), ('Mbwana Aly Samatta', 'Mbwana Aly Samatta'), ('El-Arabi', 'El-Arabi'), ('Semedo', 'Semedo'), ('Tomas Soucek', 'Tomas Soucek'), ('Higuaín', 'Higuaín'), ('Joshua Kimmich', 'Joshua Kimmich'), ('Minamino', 'Minamino'), ('Sergio Ramos', 'Sergio Ramos'), ('Jadon Sancho', 'Jadon Sancho'), ('Mane', 'Mane'), ('Foden', 'Foden'), ('Gündogan', 'Gündogan'), ('Brandt', 'Brandt'), ('Donny van de Beek', 'Donny van de Beek'), ('Wijnaldum', 'Wijnaldum'), ('Aguero', 'Aguero'), ('De Bruyne', 'De Bruyne'), ('Dzyuba', 'Dzyuba'), ('Hakim Ziyech', 'Hakim Ziyech'), ('Dennis Bonaventure', 'Dennis Bonaventure'), ('Azmoun', 'Azmoun'), ('Cheryshev', 'Cheryshev'), ('Gameiro', 'Gameiro'), ('Ferrán Torres', 'Ferrán Torres'), ('Seferovic', 'Seferovic'), ('Victor Osimhen', 'Victor Osimhen'), ('Rodrigo', 'Rodrigo'), ('Dembele', 'Dembele'), ('Lukaku', 'Lukaku'), ('Aleksey Miranchuk', 'Aleksey Miranchuk'), ('Manor Soloman', 'Manor Soloman'), ('Azpilicueta', 'Azpilicueta'), ('Jorginho Frello', 'Jorginho Frello'), ('Marcos Llorente', 'Marcos Llorente'), ('Bernat', 'Bernat'), ('Griezmann', 'Griezmann'), ('Marquinhos', 'Marquinhos'), ('Moraes', 'Moraes'), ('Sarabia', 'Sarabia'), ('Hans Hateboer', 'Hans Hateboer'), ('Insigne', 'Insigne'), ('Isco', 'Isco'), ('Peter Oladeji Olayinka', 'Peter Oladeji Olayinka'), ('Saúl', 'Saúl'), ('Felipe Monteiro', 'Felipe Monteiro'), ('Héctor Herrera', 'Héctor Herrera'), ('Kondogbia', 'Kondogbia'), ('Thomas', 'Thomas'), ('Carles Perez', 'Carles Perez'), ('Jan Boril', 'Jan Boril'), ('Tagliafico', 'Tagliafico'), ('Savic', 'Savic'), ('Konoplyanka', 'Konoplyanka'), ('Ansu Fati', 'Ansu Fati'), ('Dele Alli', 'Dele Alli'), ('Choupo-Moting', 'Choupo-Moting'), ('Krychowiak', 'Krychowiak'), ('Candreva', 'Candreva')], max_length=100, null=True),
        ),
    ]
