# Generated by Django 3.1.1 on 2020-09-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0015_auto_20200910_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-Overall']},
        ),
        migrations.AddField(
            model_name='player',
            name='imgsrc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='Name',
            field=models.CharField(choices=[('Robert Lewandowski', 'Robert Lewandowski'), ('Erling Braut Haaland', 'Erling Braut Haaland'), ('Serge Gnabry', 'Serge Gnabry'), ('Rahim Sterling', 'Rahim Sterling'), ('Memphis Depay', 'Memphis Depay'), ('Harry Kane', 'Harry Kane'), ('Dries Mertens', 'Dries Mertens'), ('Gabriel Jesus', 'Gabriel Jesus'), ('Josip Ilicic', 'Josip Ilicic'), ('Kylian Mbappe', 'Kylian Mbappe'), ('Icardi', 'Icardi'), ('Karim Benzema', 'Karim Benzema'), ('Luis Suárez', 'Luis Suárez'), ('Heung-Min Son', 'Heung-Min Son'), ('Lautaro Martínez', 'Lautaro Martínez'), ('Rodrygo', 'Rodrygo'), ('Mislav Orsic', 'Mislav Orsic'), ('Mohamed Salah', 'Mohamed Salah'), ('Emil Forsberg', 'Emil Forsberg'), ('Thomas Müller', 'Thomas Müller'), ('Cristiano Ronaldo', 'Cristiano Ronaldo'), ('M. Sabitzer', 'M. Sabitzer'), ('Timo Werner', 'Timo Werner'), ('Achraf Hakimi', 'Achraf Hakimi'), ('Quincy Promes', 'Quincy Promes'), ('Pasalic', 'Pasalic'), ('Tammy Abraham', 'Tammy Abraham'), ('Angel Di María', 'Angel Di María'), ('Neymar Jr.', 'Neymar Jr.'), ('Arkadiusz Milik', 'Arkadiusz Milik'), ('Paulo Dybala', 'Paulo Dybala'), ('Dani Olmo', 'Dani Olmo'), ('Oxlade-Chamberlain', 'Oxlade-Chamberlain'), ('Tolisso', 'Tolisso'), ('Perisic', 'Perisic'), ('João Félix', 'João Félix'), ('Hwang Hee-Chan', 'Hwang Hee-Chan'), ('Pizzi', 'Pizzi'), ('Coutinho', 'Coutinho'), ('Kingsley Coman', 'Kingsley Coman'), ('Lionel Messi', 'Lionel Messi'), ('Álvaro Morata', 'Álvaro Morata'), ('Mbwana Aly Samatta', 'Mbwana Aly Samatta'), ('El-Arabi', 'El-Arabi'), ('Nelson Semedo', 'Nelson Semedo'), ('Tomas Soucek', 'Tomas Soucek'), ('Higuaín', 'Higuaín'), ('Joshua Kimmich', 'Joshua Kimmich'), ('Takumi Minamino', 'Takumi Minamino'), ('Sergio Ramos', 'Sergio Ramos')], max_length=100, null=True),
        ),
    ]
