# Generated by Django 3.1.1 on 2020-09-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0018_auto_20200920_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
