# Generated by Django 3.1.1 on 2020-09-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0020_club_market_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='Market_Value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
