# Generated by Django 3.1.1 on 2020-09-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0022_player_market_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Market_Value',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
