# Generated by Django 3.1.1 on 2020-09-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0023_auto_20200921_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='Team',
            new_name='Club',
        ),
    ]
