# Generated by Django 3.1.1 on 2020-09-24 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0024_auto_20200924_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stadium', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='Stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ChampionsLeague.stadium'),
        ),
    ]
