# Generated by Django 3.1.1 on 2020-09-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0025_auto_20200924_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='Stadium',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ChampionsLeague.stadium'),
        ),
    ]
