# Generated by Django 3.1.1 on 2020-09-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0026_auto_20200924_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='Market_Value',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
