# Generated by Django 3.1.1 on 2020-09-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionsLeague', '0027_auto_20200924_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Captain', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='is_Captain',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='Club_Captain',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ChampionsLeague.captain'),
        ),
    ]
